-- Labels/Tags an Karten (Issue #176)
-- ---------------------------------------------------------------------------
-- Board-scoped Labels (Name + Farbe) und ihre Zuordnung zu Karten. Labelverwaltung ist ein
-- Board-Recht (BOARD_UPDATE); die Zuordnung an Karten ein Ticket-Recht (TICKET_UPDATE).

CREATE TABLE label (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id bigint       NOT NULL REFERENCES board (id) ON DELETE CASCADE,
    name     varchar(60)  NOT NULL,
    color    varchar(20)  NOT NULL,
    CONSTRAINT uq_label_board_name UNIQUE (board_id, name)
);
CREATE INDEX idx_label_board ON label (board_id);

CREATE TABLE card_label (
    card_id  bigint NOT NULL REFERENCES card (id) ON DELETE CASCADE,
    label_id bigint NOT NULL REFERENCES label (id) ON DELETE CASCADE,
    CONSTRAINT pk_card_label PRIMARY KEY (card_id, label_id)
);
CREATE INDEX idx_card_label_label ON card_label (label_id);
