-- Karten-Aktivitätsverlauf (Issue #177)
-- ---------------------------------------------------------------------------
-- Chronologische Historie der Änderungen je Karte (angelegt, verschoben, bearbeitet,
-- zugewiesen, archiviert, wiederhergestellt). Getrennt vom Plattform-Audit-Log (#1).

CREATE TABLE card_activity (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id       bigint         NOT NULL REFERENCES card (id) ON DELETE CASCADE,
    actor_user_id bigint         REFERENCES app_user (id) ON DELETE SET NULL,
    type          varchar(20)    NOT NULL,
    detail        varchar(500)   NOT NULL,
    created_at    timestamptz(6) NOT NULL
);
CREATE INDEX idx_card_activity_card ON card_activity (card_id, created_at);
