-- manban — konsolidierte Postgres-Baseline (Issue F2).
-- Board-scopedes Modell, eigene Auth (kein Keycloak), Anhänge über Objektspeicher.
-- Postgres-Idiome: GENERATED BY DEFAULT AS IDENTITY, GENERATED ... STORED, CASE statt IF(),
-- TIMESTAMP(6) (timestamptz), separate CREATE INDEX, Trigger für updated_at.

-- Gemeinsame Trigger-Funktion: setzt updated_at bei jedem UPDATE.
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Auth / Benutzer
-- ---------------------------------------------------------------------------

CREATE TABLE app_user (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          varchar(320)   NOT NULL,
    password_hash  varchar(255)   NOT NULL,
    display_name   varchar(120)   NOT NULL,
    email_verified boolean        NOT NULL DEFAULT false,
    platform_role  varchar(16)    NOT NULL DEFAULT 'USER',
    created_at     timestamptz(6) NOT NULL DEFAULT now(),
    updated_at     timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_platform_role CHECK (platform_role IN ('ADMIN', 'USER'))
);
CREATE TRIGGER trg_app_user_updated_at BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE email_verification_token (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash varchar(255)   NOT NULL,
    expires_at timestamptz(6) NOT NULL,
    used_at    timestamptz(6),
    CONSTRAINT uq_email_verification_token_hash UNIQUE (token_hash)
);
CREATE INDEX idx_email_verification_token_user ON email_verification_token (user_id);

CREATE TABLE password_reset_token (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash varchar(255)   NOT NULL,
    expires_at timestamptz(6) NOT NULL,
    used_at    timestamptz(6),
    CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash)
);
CREATE INDEX idx_password_reset_token_user ON password_reset_token (user_id);

-- Nur Schema (2FA-Vorbereitung) — im MVP ungenutzt.
CREATE TABLE user_mfa_credential (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    type       varchar(16)    NOT NULL,
    secret     varchar(255),
    public_key text,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT ck_user_mfa_type CHECK (type IN ('TOTP', 'WEBAUTHN'))
);
CREATE INDEX idx_user_mfa_credential_user ON user_mfa_credential (user_id);

-- PAT (aus Toolbox portiert, Issue A4): X-Kanban-Token, Format tk_<64hex>.
CREATE TABLE kanban_access_token (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name         varchar(120)   NOT NULL,
    token_hash   varchar(255)   NOT NULL,
    display_name varchar(120),
    created_at   timestamptz(6) NOT NULL DEFAULT now(),
    last_used_at timestamptz(6),
    revoked      boolean        NOT NULL DEFAULT false,
    CONSTRAINT uq_kanban_access_token_hash UNIQUE (token_hash)
);
CREATE INDEX idx_kanban_access_token_user ON kanban_access_token (user_id);

-- ---------------------------------------------------------------------------
-- Projekt (Tenant) + RBAC
-- ---------------------------------------------------------------------------

CREATE TABLE project (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(200)   NOT NULL,
    owner_user_id bigint         NOT NULL REFERENCES app_user (id),
    created_at    timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_project_owner ON project (owner_user_id);

CREATE TABLE project_membership (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint         NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    user_id    bigint         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role       varchar(16)    NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_membership UNIQUE (project_id, user_id),
    CONSTRAINT ck_project_membership_role CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER'))
);
CREATE INDEX idx_project_membership_user ON project_membership (user_id);

CREATE TABLE project_invitation (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  bigint         NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    email       varchar(320)   NOT NULL,
    role        varchar(16)    NOT NULL,
    token_hash  varchar(255)   NOT NULL,
    expires_at  timestamptz(6) NOT NULL,
    accepted_at timestamptz(6),
    invited_by  bigint         REFERENCES app_user (id),
    CONSTRAINT uq_project_invitation_token UNIQUE (token_hash),
    CONSTRAINT ck_project_invitation_role CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER'))
);
CREATE INDEX idx_project_invitation_project ON project_invitation (project_id);

CREATE TABLE permission (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         varchar(64) NOT NULL,
    description varchar(255),
    CONSTRAINT uq_permission_key UNIQUE (key)
);

CREATE TABLE role_permission (
    role          varchar(16) NOT NULL,
    permission_id bigint      NOT NULL REFERENCES permission (id) ON DELETE CASCADE,
    CONSTRAINT pk_role_permission PRIMARY KEY (role, permission_id),
    CONSTRAINT ck_role_permission_role CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER'))
);

-- ---------------------------------------------------------------------------
-- Board + Karten (board-scoped)
-- ---------------------------------------------------------------------------

CREATE TABLE board (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint         NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name       varchar(200)   NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_board_project ON board (project_id);

CREATE TABLE board_column (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id  bigint      NOT NULL REFERENCES board (id) ON DELETE CASCADE,
    name      varchar(120) NOT NULL,
    position  integer     NOT NULL,
    wip_limit integer,
    CONSTRAINT uq_board_column_position UNIQUE (board_id, position)
);
CREATE INDEX idx_board_column_board ON board_column (board_id);

CREATE TABLE card (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id           bigint         NOT NULL REFERENCES board (id) ON DELETE CASCADE,
    column_id          bigint         NOT NULL REFERENCES board_column (id),
    number             integer        NOT NULL,
    title              varchar(300)   NOT NULL,
    description        text,
    position_in_column integer        NOT NULL,
    archived           boolean        NOT NULL DEFAULT false,
    -- Positions-Integrität: archivierte Karten liegen außerhalb des aktiven Namespace
    -- (active_position = NULL) und kollidieren daher nicht mit dem Unique-Constraint.
    active_position    integer GENERATED ALWAYS AS (CASE WHEN archived THEN NULL ELSE position_in_column END) STORED,
    moved_to_done_at   timestamptz(6),
    created_by         bigint         REFERENCES app_user (id),
    created_at         timestamptz(6) NOT NULL DEFAULT now(),
    updated_at         timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT uq_card_number UNIQUE (board_id, number),
    CONSTRAINT uq_card_active_position UNIQUE (board_id, column_id, active_position)
);
CREATE INDEX idx_card_board ON card (board_id);
CREATE INDEX idx_card_column ON card (column_id);
CREATE TRIGGER trg_card_updated_at BEFORE UPDATE ON card
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE card_dependency (
    card_id                bigint  NOT NULL REFERENCES card (id) ON DELETE CASCADE,
    depends_on_card_number integer NOT NULL,
    CONSTRAINT pk_card_dependency PRIMARY KEY (card_id, depends_on_card_number)
);

CREATE TABLE comment (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id        bigint         NOT NULL REFERENCES card (id) ON DELETE CASCADE,
    author_user_id bigint         REFERENCES app_user (id),
    author_name    varchar(120)   NOT NULL,
    body           text           NOT NULL,
    created_at     timestamptz(6) NOT NULL DEFAULT now(),
    updated_at     timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_comment_card ON comment (card_id);
CREATE TRIGGER trg_comment_updated_at BEFORE UPDATE ON comment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Anhang-Metadaten; Blob liegt in MinIO (Objektspeicher), nicht in der DB.
CREATE TABLE attachment_meta (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id      bigint         NOT NULL REFERENCES card (id) ON DELETE CASCADE,
    filename     varchar(255)   NOT NULL,
    content_type varchar(127)   NOT NULL,
    size         bigint         NOT NULL,
    object_key   varchar(512)   NOT NULL,
    created_at   timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT uq_attachment_object_key UNIQUE (object_key)
);
CREATE INDEX idx_attachment_meta_card ON attachment_meta (card_id);

-- ---------------------------------------------------------------------------
-- Seed: Rechte-Katalog + feste Rollen-Rechte-Matrix
-- ---------------------------------------------------------------------------

INSERT INTO permission (key, description) VALUES
    ('CARD_CREATE',       'Karten anlegen'),
    ('CARD_MOVE',         'Karten verschieben'),
    ('CARD_DELETE',       'Karten archivieren/löschen'),
    ('COLUMN_EDIT',       'Spalten bearbeiten'),
    ('BOARD_CREATE',      'Boards anlegen'),
    ('BOARD_DELETE',      'Boards löschen'),
    ('MEMBER_INVITE',     'Mitglieder einladen'),
    ('MEMBER_REMOVE',     'Mitglieder entfernen/Rolle ändern'),
    ('PROJECT_EDIT',      'Projekt bearbeiten'),
    ('PROJECT_DELETE',    'Projekt löschen'),
    ('COMMENT_CREATE',    'Kommentare schreiben'),
    ('ATTACHMENT_UPLOAD', 'Anhänge hochladen');

-- MEMBER: Karten, Kommentare, Anhänge.
INSERT INTO role_permission (role, permission_id)
SELECT 'MEMBER', id FROM permission
WHERE key IN ('CARD_CREATE', 'CARD_MOVE', 'CARD_DELETE', 'COMMENT_CREATE', 'ATTACHMENT_UPLOAD');

-- ADMIN: MEMBER + Board/Spalten/Mitgliederverwaltung.
INSERT INTO role_permission (role, permission_id)
SELECT 'ADMIN', id FROM permission
WHERE key IN ('CARD_CREATE', 'CARD_MOVE', 'CARD_DELETE', 'COMMENT_CREATE', 'ATTACHMENT_UPLOAD',
              'COLUMN_EDIT', 'BOARD_CREATE', 'BOARD_DELETE', 'MEMBER_INVITE', 'MEMBER_REMOVE');

-- OWNER: alle Rechte.
INSERT INTO role_permission (role, permission_id)
SELECT 'OWNER', id FROM permission;

-- VIEWER: nur lesen -> keine Schreibrechte in dieser Tabelle.
