-- Transaktionale Outbox: Seiteneffekte überleben den Commit, nicht das Rollback (Issue #501)
-- ---------------------------------------------------------------------------
-- Ein fachlicher Use-Case merkt sein Vorhaben (Mail versenden, Objekt löschen) INNERHALB seiner
-- Transaktion hier vor; ein Worker arbeitet es danach ab. Damit gilt beides: Ein Rollback lässt
-- kein Vorhaben zurück, und ein Absturz zwischen Commit und Seiteneffekt verliert es nicht — der
-- nächste Lauf findet den Eintrag noch.
--
-- idempotency_key ist eindeutig: Derselbe fachliche Anlass ergibt genau einen Eintrag, auch wenn
-- der Use-Case zweimal läuft. Der Schreibweg nutzt ihn per ON CONFLICT DO NOTHING, damit der
-- zweite Aufrufer keinen Constraint-Fehler in seine Fachtransaktion bekommt.
--
-- payload trägt bewusst nur Referenzen, keine Klartext-Geheimnisse (Verifikations- und
-- Reset-Links enthalten Tokens). Zusätzlich leert die Anwendung das Feld, sobald ein Eintrag
-- DONE oder FAILED erreicht — Begründung im Javadoc von OutboxEntry.
--
-- Aufbewahrung: Der Retention-Job löscht ausschließlich DONE. FAILED bleibt stehen, sonst wäre
-- ein nie ausgeführter Seiteneffekt lautlos verschwunden.

CREATE TABLE outbox_entry (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      varchar(100)   NOT NULL,
    idempotency_key varchar(200)   NOT NULL,
    payload         text           NOT NULL,
    status          varchar(20)    NOT NULL,
    attempts        integer        NOT NULL DEFAULT 0,
    created_at      timestamptz(6) NOT NULL DEFAULT now(),
    next_attempt_at timestamptz(6) NOT NULL DEFAULT now(),
    completed_at    timestamptz(6),
    last_error      varchar(1000),
    CONSTRAINT uq_outbox_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING', 'DONE', 'FAILED')),
    CONSTRAINT ck_outbox_attempts CHECK (attempts >= 0)
);

-- Der Worker fragt ausschließlich nach fälligen offenen Einträgen; der Teilindex bleibt deshalb
-- klein, auch wenn die Tabelle viele erledigte Zeilen enthält.
CREATE INDEX idx_outbox_due ON outbox_entry (next_attempt_at, id) WHERE status = 'PENDING';

-- Gegenstück für den Aufräum-Job, der nur erledigte Einträge nach Abschlusszeitpunkt löscht.
CREATE INDEX idx_outbox_completed ON outbox_entry (completed_at) WHERE status = 'DONE';
