-- Auswertung der Nachtlaeufe: je Projekt die aufbewahrten Laeufe samt Arbeitspaketen (Plan #718)
-- ---------------------------------------------------------------------------
-- Der Nacht-Runner schreibt sein Protokoll lokal; ausgewertet wird es im Browser (Issue #720), und
-- an den Server geht allein die verdichtete Auswertung. Diese beiden Tabellen sind ihr Speicher.
--
-- started_at ist der fachliche Schluessel eines Laufs (Plan #718, A4). uq_night_run_project_started
-- traegt deshalb die Duplikatserkennung: Der Schreibweg nutzt sie per
-- ON CONFLICT (project_id, started_at) DO NOTHING RETURNING id, damit ein zweites Hochladen
-- desselben Protokolls keine Constraint-Verletzung in die fachliche Transaktion traegt, sondern
-- schlicht keine Zeile liefert. Ein zusaetzlicher CREATE INDEX auf denselben Spalten entfaellt:
-- Postgres legt zum UNIQUE-Constraint bereits einen an.
--
-- Zustand, Modus und Fehlerklasse stehen als varchar(n) + CHECK (... IN (...)) und nicht als
-- PG-Enum (Projektkonvention). Verbindliche Fassung der drei Wertelisten ist der Parser
-- frontend/src/lib/nightRunLog.ts (Plan #718, A13); NightRunErrorClassSyncTest haelt Parser,
-- Java-Typen und diese Datei gleich. Die Spaltenlaengen sind an den laengsten Konstanten bemessen
-- (IMPLEMENTATION = 14, YELLOW = 6, AWAITING_DECISION = 18) und mit Reserve versehen — reicht eine
-- Laenge kuenftig nicht, wird die Spalte verbreitert, nicht die Werteliste gekuerzt.
--
-- 4000 ist die Auszugsgrenze aus Plan #718, A16 — fuer night_run.unparsed_sample und
-- night_run_item.excerpt. Dieselbe Zahl steht als NightRunLimits.EXCERPT_MAX in
-- nightrun/domain und als NIGHT_RUN_EXCERPT_MAX in frontend/src/lib/nightRunLog.ts; die
-- Spaltenlaenge selbst ist die Pruefung, ein zusaetzlicher CHECK auf char_length waere derselbe
-- Waechter ein zweites Mal. Gezaehlt wird hier in Codepoints, in Java und TypeScript in
-- UTF-16-Codeeinheiten — Postgres ist damit nie enger als die Anwendung.
--
-- title ist so lang wie seine Quelle card.title (varchar(300), Baseline): Ein Schnappschuss kann
-- nie laenger sein als das Original.

CREATE TABLE night_run (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      bigint         NOT NULL,
    started_at      timestamptz(6) NOT NULL,
    mode            varchar(20)    NOT NULL,
    duration_ms     bigint         NOT NULL,
    processed_count integer        NOT NULL,
    skipped_count   integer        NOT NULL,
    unparsed_count  integer        NOT NULL,
    unparsed_sample varchar(4000),
    created_at      timestamptz(6) NOT NULL,
    CONSTRAINT fk_night_run_project FOREIGN KEY (project_id)
        REFERENCES project (id) ON DELETE CASCADE,
    CONSTRAINT uq_night_run_project_started UNIQUE (project_id, started_at),
    CONSTRAINT ck_night_run_mode CHECK (mode IN ('IMPLEMENTATION', 'REVIEW'))
);

CREATE TABLE night_run_item (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    night_run_id bigint       NOT NULL,
    card_number  integer      NOT NULL,
    title        varchar(300) NOT NULL,
    state        varchar(20)  NOT NULL,
    error_class  varchar(40),
    duration_ms  bigint,
    commit_hash  varchar(40),
    excerpt      varchar(4000),
    CONSTRAINT fk_night_run_item_run FOREIGN KEY (night_run_id)
        REFERENCES night_run (id) ON DELETE CASCADE,
    CONSTRAINT ck_night_run_item_state CHECK (state IN ('GREEN', 'YELLOW', 'RED', 'GREY')),
    CONSTRAINT ck_night_run_item_error_class CHECK (error_class IN (
        'CHECKS_RED', 'CHECKS_NOT_STARTED', 'DEPENDENCY_UNMET', 'UNEXPECTED_STATE',
        'HARD_ABORT', 'AWAITING_DECISION', 'REVIEWER_FAILED'))
);

-- Die Korrelation zwischen state und error_class steht bewusst NICHT als CHECK hier: Die
-- Zustandsliste kann sich unabhaengig von den Fehlerklassen weiterentwickeln, und ein
-- korrelierender CHECK muesste bei jeder Aenderung mitwandern. Belegt wird sie in
-- NightRunRepositoryIT.

-- Traegt die Zaehlung der Fehlerklassen ueber die aufbewahrten Laeufe eines Projekts
-- (SELECT error_class, count(DISTINCT night_run_id) ... GROUP BY error_class).
CREATE INDEX idx_night_run_item_run_error ON night_run_item (night_run_id, error_class);
