-- Budgets, ihre Herkunft und die Kennzahlen je Stufe eines Kettenlaufs (Issue #1112, Plan #1110).
--
-- Bis hierher lagen Zeitvorgaben, Kostenbudget, die Herkunft der Vorgaben und die Kennzahlen je
-- Stufe allein im Browser: Ein ohne Handgriff gemeldeter Kettenlauf zeigte weniger als ein
-- eingelesener, und kein Neuladen ueberstand die Angaben. Diese Migration legt ihren Ort an.
--
-- Die fuenf Budget-Spalten stehen an night_run und nicht in einer eigenen Tabelle (E2): Zu einem
-- Lauf gehoert genau ein Budget, ein Join fuer ein 1:1-Verhaeltnis waere ohne Gewinn, und der
-- Ringpuffer muesste beim Verdraengen eine zweite Tabelle mitfuehren.
--
-- Kein Backfill (E16) -- wie V32 und V34 es fuer die Verbrauchsspalten schon gehalten haben. Fuer
-- Laeufe von vor dieser Migration sind die Werte nicht rekonstruierbar. NULL heisst hier "nicht
-- angegeben" bzw. "nicht gemeldet" und nie Null; eine 0 behauptete, der Lauf habe fuer diese Stufe
-- keine Zeit bekommen oder nichts verbraucht.

ALTER TABLE night_run
    ADD COLUMN budget_plan_min       integer,
    ADD COLUMN budget_review_min     integer,
    ADD COLUMN budget_pakete_min     integer,
    ADD COLUMN budget_abdeckung_min  integer,
    ADD COLUMN budget_kosten_usd     numeric(12,6),
    ADD COLUMN budget_origin         varchar(16),
    ADD COLUMN budget_default_fields varchar(200);

-- Die Herkunft steht in zwei Spalten und nicht in einer einzigen Textspalte, in der die leere
-- Zeichenkette "eingestellt" bedeutete (E3): Die Anzeige muss drei Aussagen unterscheiden --
-- eingestellt, aus Voreinstellungen ergaenzt (dann mit den Feldnamen), nicht angegeben --, und die
-- Unterscheidung "leere Zeichenkette gegen NULL" ebnet frueher oder spaeter ein Serialisierer, ein
-- Trim oder eine Migration still ein. budget_origin IS NULL heisst "nicht angegeben";
-- budget_default_fields ist nur bei DEFAULTED gefuellt.
--
-- varchar(n) + CHECK statt PG-Enum, dem Muster von origin aus V32 und kind aus V34 folgend
-- (Projektkonvention). 16 ist an DEFAULTED = 9 bemessen und mit Reserve versehen.
ALTER TABLE night_run
    ADD CONSTRAINT ck_night_run_budget_origin
        CHECK (budget_origin IN ('CONFIGURED', 'DEFAULTED'));

-- Modellzeit und Zuege gehoeren zum Verbrauch (E1) und stehen darum neben den vier Spalten aus
-- V32 -- an night_run und an night_run_item gleichermassen, wie schon dort. Die Modellzeit ist
-- nicht die Wanduhr-Dauer aus duration_ms: Die schliesst Werkzeugaufrufe und Wartezeiten ein.
ALTER TABLE night_run
    ADD COLUMN model_duration_ms bigint,
    ADD COLUMN turns             integer;

ALTER TABLE night_run_item
    ADD COLUMN model_duration_ms bigint,
    ADD COLUMN turns             integer;

-- Die Stufen haengen am Arbeitspaket und nicht am Lauf: Ein Kettenlauf fuehrt mehrere Vorgaenge,
-- und die Kennzahlen einer Stufe gehoeren zu genau einem davon. Der Fremdschluessel zeigt auf
-- night_run_item.id und ausdruecklich nicht auf (night_run_id, card_number) -- das ist kein
-- Schluessel: Zwei Vorgaenge eines Laufs koennen dieselbe Karte betreffen.
--
-- ON DELETE CASCADE, nicht SET NULL wie bei night_run_item aus V33: Eine Stufe ohne ihren Vorgang
-- waere keine Aussage. Das Paket selbst ueberdauert die Verdraengung seines Laufs und nimmt seine
-- Stufen dabei mit.
CREATE TABLE night_run_item_stage (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    night_run_item_id   bigint      NOT NULL,
    stage               varchar(16) NOT NULL,
    duration_ms         bigint,
    cost_usd            numeric(12,6),
    input_tokens        bigint,
    output_tokens       bigint,
    cached_input_tokens bigint,
    model_duration_ms   bigint,
    turns               integer,
    CONSTRAINT fk_night_run_item_stage_item FOREIGN KEY (night_run_item_id)
        REFERENCES night_run_item (id) ON DELETE CASCADE,
    CONSTRAINT ck_night_run_item_stage_stage
        CHECK (stage IN ('PLAN', 'REVIEW', 'PAKETE', 'ABDECKUNG')),
    CONSTRAINT uq_night_run_item_stage UNIQUE (night_run_item_id, stage)
);

-- Traegt das Nachladen der Stufen zu einer Menge von Arbeitspaketen
-- (WHERE night_run_item_id IN (...)). Der Index zum UNIQUE-Constraint fuehrt dieselbe Spalte
-- vorn und traegt die Abfrage ebenfalls; benannt und angelegt wird er hier dennoch eigens, weil
-- der Zugriffsweg nicht an einer Eindeutigkeitszusage haengen soll, die spaeter fallen koennte.
CREATE INDEX idx_night_run_item_stage_item ON night_run_item_stage (night_run_item_id);
