-- Protokoll der Sicherungslaeufe (Issue #826, Plan #825)
-- ---------------------------------------------------------------------------
-- Die Sicherung laeuft als eigener Container ausserhalb der Anwendung (E1) und meldet ihren
-- Ausgang ueber die Datenbank statt ueber HTTP (E2): Der Container hat Datenbankzugang ohnehin,
-- und ein interner Endpunkt waere tot, sobald die Anwendung haengt — dann bliebe ausgerechnet das
-- Scheitern unprotokolliert. Die Tabelle gehoert Flyway; der Container schreibt ausschliesslich
-- INSERT.
--
-- kind und outcome stehen als varchar(n) + CHECK (... IN (...)) und nicht als PG-Enum
-- (Projektkonvention, siehe V29__night_run.sql). Die Werte sind hier klein geschrieben, weil der
-- schreibende Teil ein Shell-Skript ist und nicht die Anwendung: Er setzt die Zeichenkette
-- woertlich ein. Der Lesepfad bildet sie in der Persistenzschicht auf die Java-Konstanten ab.
--
-- bytes und detail sind bewusst optional: Ein gelungener Lauf hat keinen Grund zu nennen, ein
-- gescheiterter keine Groesse zu melden.
--
-- Der Index traegt die einzige Abfrage des Lesepfads — je Art der juengste Lauf und der juengste
-- gelungene Lauf. Die Filterung nach outcome bleibt draussen: Die Tabelle waechst langsam (wenige
-- Zeilen je Takt), und ein zweiter Index kostete jeden INSERT des Containers mit.
CREATE TABLE backup_run (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        varchar(20)    NOT NULL,
    started_at  timestamptz(6) NOT NULL,
    finished_at timestamptz(6),
    outcome     varchar(20)    NOT NULL,
    detail      varchar(4000),
    bytes       bigint,
    CONSTRAINT ck_backup_run_kind CHECK (kind IN ('basis', 'wal', 'spiegel', 'offsite')),
    CONSTRAINT ck_backup_run_outcome CHECK (outcome IN ('erfolg', 'fehlschlag'))
);

CREATE INDEX idx_backup_run_kind_started ON backup_run (kind, started_at DESC);
