-- ---------------------------------------------------------------------------
-- Morgenmeldung je Lauf: releasePreparation aus POST /api/kanban/night-runs
-- (Issue #1456, Plan #1447 E12)
--
-- Das Kit meldet in der bestehenden Laufmeldung, ob und wie die Nacht eine
-- Veroeffentlichung vorbereitet hat. Bis hierher verwarf Jackson das Feld still.
-- Zwei Tabellen statt einer jsonb-Spalte an night_run: Der Bestand nutzt nirgends
-- jsonb, und Tabellen halten ihre Pruefungen per Constraint.
--
-- Rein additiv: Eine aeltere App-Version laeuft gegen dieses Schema unveraendert,
-- sie kennt die beiden Tabellen nur nicht. Kein Backfill -- Laeufe vor dieser
-- Migration tragen keine Morgenmeldung.
--
-- Rueckweg (Flyway Community kennt kein Undo; von Hand, in dieser Reihenfolge,
-- danach die Zeile von V48 aus flyway_schema_history loeschen):
--   DROP TABLE night_run_release_entry;
--   DROP TABLE night_run_release_preparation;
-- ---------------------------------------------------------------------------

-- Eine Zeile je Lauf: night_run_id ist zugleich Primaerschluessel. ON DELETE CASCADE,
-- weil eine Morgenmeldung ohne ihren Lauf keine Aussage waere; der Ringpuffer nimmt
-- sie beim Verdraengen mit. Laengen wie die Grenzen im Request (NightRunIngestController).
-- varchar(n) + CHECK statt PG-Enum, dem Muster von budget_origin aus V37 folgend.
CREATE TABLE night_run_release_preparation (
    night_run_id bigint       PRIMARY KEY,
    result       varchar(16)  NOT NULL,
    commit_hash  varchar(40),
    version      varchar(100),
    red_check    varchar(300),
    received_at  timestamptz  NOT NULL,
    CONSTRAINT fk_night_run_release_preparation_run FOREIGN KEY (night_run_id)
        REFERENCES night_run (id) ON DELETE CASCADE,
    CONSTRAINT ck_night_run_release_preparation_result
        CHECK (result IN ('GREEN', 'GREEN_PENDING', 'RED', 'NOT_PREPARED'))
);

-- Die drei Listen der Meldung in einer Tabelle, unterschieden nach Art: CARD und
-- RED_CARD tragen eine Kartennummer, PENDING einen Text. position haelt die
-- gemeldete Reihenfolge je Art. Der Fremdschluessel zeigt auf die Morgenmeldung, nicht
-- auf den Lauf: Ersetzt eine neue Meldung die alte, fallen ihre Eintraege mit.
CREATE TABLE night_run_release_entry (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    night_run_id bigint       NOT NULL,
    kind         varchar(16)  NOT NULL,
    position     integer      NOT NULL,
    card_number  integer,
    text         varchar(300),
    CONSTRAINT fk_night_run_release_entry_preparation FOREIGN KEY (night_run_id)
        REFERENCES night_run_release_preparation (night_run_id) ON DELETE CASCADE,
    CONSTRAINT ck_night_run_release_entry_kind
        CHECK (kind IN ('CARD', 'RED_CARD', 'PENDING')),
    CONSTRAINT ck_night_run_release_entry_shape
        CHECK ((kind IN ('CARD', 'RED_CARD') AND card_number IS NOT NULL AND text IS NULL)
            OR (kind = 'PENDING' AND text IS NOT NULL AND card_number IS NULL)),
    -- Der Index zu dieser Eindeutigkeit fuehrt night_run_id vorn und traegt das
    -- Nachladen der Eintraege zu einer Menge von Laeufen.
    CONSTRAINT uq_night_run_release_entry UNIQUE (night_run_id, kind, position)
);
