-- Spalten-Zykluszeit-Tracking (Issue #170)
-- ---------------------------------------------------------------------------
-- Historie der Spaltenaufenthalte je Karte: bei jedem Spaltenwechsel wird die verlassene
-- Zeile geschlossen (left_at + duration_seconds) und für die Zielspalte eine neue, offene
-- Zeile eröffnet. Generisch pro column_id (kein festes Spalten-Enum). column_name ist ein
-- Snapshot zum Eintrittszeitpunkt, da Spalten umbenannt werden können. Grundlage für das
-- KPI-Dashboard (Folge-Issues).

CREATE TABLE card_column_transition (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id          bigint         NOT NULL REFERENCES card (id) ON DELETE CASCADE,
    -- Spalten können gelöscht werden; die Historie bleibt erhalten (column_id wird NULL).
    column_id        bigint         REFERENCES board_column (id) ON DELETE SET NULL,
    column_name      varchar(120)   NOT NULL,
    entered_at       timestamptz(6) NOT NULL,
    left_at          timestamptz(6),
    duration_seconds bigint
);
CREATE INDEX idx_cct_card ON card_column_transition (card_id);
CREATE INDEX idx_cct_column ON card_column_transition (column_id);
CREATE INDEX idx_cct_entered ON card_column_transition (entered_at);

-- Backfill: pro aktiver Nicht-Epic-Karte eine offene Zeile in ihrer aktuellen Spalte.
-- Kein fingierter historischer Zeitstempel — das Tracking startet sauber ab Deploy.
INSERT INTO card_column_transition (card_id, column_id, column_name, entered_at)
SELECT c.id, c.column_id, bc.name, now()
FROM card c
JOIN board_column bc ON bc.id = c.column_id
WHERE c.archived = false AND c.type <> 'EPIC';
